### ISSUE TITLE
Building the code with Xcode.

### ISSUE THREAD

**Issue by adamist521** [liuliu/klaus#2]
I have cloned Klaus and tried to build it with my xcode( xcode 6 beta-5).
It somehow fails due to file "arm_neon.h".
error message says that "NEON support not enabled".

Any clue how to solve this prob? 
On which Xcode does it succeed to build?

**Comment by soumith** [comment]
add the compiler flag -mfpu=neon

**Comment by soumith** [comment]
also, if your target is Simulator, it wont find NEON, your target has to be a device.

**Comment by liuliu** [comment]
I only targeted to device, if you want to target to simulator, have to manually remove the compiler flag -D HAVE_NEON in ccv Xcode project.

**Comment by ayn** [comment]
**MUCH** faster! :zap:
