### ISSUE TITLE
Running speed

### ISSUE THREAD

**Issue by zhweiyu** [liuliu/klaus#3]
Hey. I got it run on my iphone5s. Somehow each image takes 30 seconds instead of 3 seconds. Do you have any suggestion on what may go wrong?

**Comment by liuliu** [comment]
Can you detail your setup, Xcode version etc and how to comple Klaus onto device?

**Comment by zhweiyu** [comment]
Setup :  xcode6 - Beta 7 with ios 8 sdk (beta 5)

List of changes to make it compile

add zlib, libjpeg, libpng. Also I manually wired ccv_trace to use
accelerate framework.

[image: Inline image 1]

I will do some profiling to break now the time.

Thanks a lot for your time.

On Sat, Sep 6, 2014 at 6:26 AM, Liu Liu notifications@github.com wrote:

> Can you detail your setup, Xcode version etc and how to comple Klaus onto
> device?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/liuliu/klaus/issues/3#issuecomment-54712255.

## 

Sincerely

Weiyu Zhang

**Comment by soumith** [comment]
are you building in release mode or Debug? :dancers:

**Comment by zhweiyu** [comment]
Oops.. Amature xcode mistake. 

I built the release (using command + I) . The running time is down to 10 seconds. 

Any other things could go wrong ?

**Comment by soumith** [comment]
make sure NEON is enabled.

**Comment by zhweiyu** [comment]
The building architecture is armv7, google told me NEON is enabled by default. I added -mfloat-abi=softfp -mfpu=neon as well, no change. 

I changed the optimization flag to -Ofast , this improve the running speed to 8s. 

Any other ideas ? 

Thanks soumith!

**Comment by soumith** [comment]
maybe try compiling for arm64? isn't iphone5s arm64?

**Comment by zhweiyu** [comment]
Sorry . It's armv7 & arm64. Please see attached for architecture setting. 

![screen shot 2014-09-06 at 10 52 16 am](https://cloud.githubusercontent.com/assets/1792626/4175971/a95ecef6-35ee-11e4-8738-2818afb3d98b.png)

**Comment by liuliu** [comment]
Can you make sure your ccv project setup still have this flag on (-D HAVE_NEON)? It sounds suspicious to me that your Release mode / Debug mode time is different (I added -O3 to the source file already).

https://github.com/liuliu/klaus/blob/master/ccv/ccv.xcodeproj/project.pbxproj#L24

**Comment by zhweiyu** [comment]
Thanks :)

That solves the problem. Somehow the NEON flag disappeared. I introduced
them back, and now it runs 1.x seconds on iphone 5s [?]

On Sat, Sep 6, 2014 at 12:27 PM, Liu Liu notifications@github.com wrote:

> Can you make sure your ccv project setup still have this flag on (-D
> HAVE_NEON)? It sounds suspicious to me that your Release mode / Debug mode
> time is different (I added -O3 to the source file already).
> 
> https://github.com/liuliu/klaus/blob/master/ccv/ccv.xcodeproj/project.pbxproj#L24
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/liuliu/klaus/issues/3#issuecomment-54725562.

## 

Sincerely

Weiyu Zhang

**Comment by liuliu** [comment]
I haven't timed on 5S, make sure the result is reasonable, then yeah, the time is probably right (on iPhone 5, it is about 3 seconds).
